services:
  nginx:
    build: requirements/nginx
    image: nginx:v1.0.0
    container_name: nginx
    env_file:
      - ./.env
    ports:
      - "443:443"
    volumes:
      - wp_storage:/var/www/html/
    networks:
      - inception
    restart: unless-stopped
    depends_on:
      - wordpress
  wordpress:
    build: requirements/wordpress
    image: wordpress:v1.0.0
    container_name: wordpress
    env_file:
      - ./.env
    volumes:
      - wp_storage:/var/www/html/
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
  mariadb:
    build: requirements/mariadb
    image: mariadb:v1.0.0
    container_name: mariadb
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - db_storage:/var/lib/mysql/
    restart: unless-stopped
  redis:
    build : requirements/bonus/redis
    image: redis:v1.0.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: unless-stopped
  ftp:
    build: requirements/bonus/ftp
    image: ftps:v1.0.0
    container_name: ftp
    ports:
      - "10000-10100:10000-10100"
      - "21:21"
    networks:
      - inception
    env_file:
      - ./.env
    volumes:
      - wp_storage:${FTP_DIR}
    depends_on:
      - wordpress
      - nginx
      - mariadb
    restart: unless-stopped
  web:
    build: requirements/bonus/web
    image: web:v1.0.0
    container_name: web
    ports:
      - "80:80"
    networks:
      - inception
    restart: unless-stopped
  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    image: adminer:v1.0.0
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped
  portainer:
    build: requirements/bonus/portainer
    image: portainer:v1.0.0
    container_name: portainer
    env_file:
      - ./.env
    networks:
      - inception
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mariadb
      - wordpress
      - redis
      - ftp
      - adminer
      - nginx
    restart: unless-stopped
networks:
  inception:
    driver: bridge
volumes:
  portainer_data:
  db_storage:
    driver: local
    driver_opts:
      type: none
      device: /home/belguabd/data/db
      o: bind
  wp_storage:
    driver: local
    driver_opts:
      type: none
      device: /home/belguabd/data/wp
      o: bind