services:
  nginx:
    build: ./nginx
    container_name: nginx
    env_file:
      - ./.env
    ports:
      - "80:80"                      
    volumes:
      - wp_storage:/var/www/html/
    networks:
      - inception
    depends_on:
      - wordpress
      - adminer
  wordpress:
    build: ./wordpress
    container_name: wordpress
    env_file:
      - ./.env
    ports:
      - "9000:9000"
    volumes:
      - wp_storage:/var/www/html/
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
  mariadb:
    build: ./mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - db_storage:/var/lib/mysql/
  redis:
    build : ./bonus/redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception
  ftp:
    build: ./bonus/ftp
    container_name: ftp
    ports:
      - "10000-10100:10000-10100"
    networks:
      - inception
    env_file:
      - ./.env
    volumes:
      - wp_storage:${FTP_DIR}
    depends_on:
      - wordpress
  # web:
  #   build: ./bonus/web
  #   container_name: web
  #   ports:
  #     - "80:80"
  adminer:
    build: ./bonus/adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb
    
networks:
  inception:
    driver: bridge
volumes:
  db_storage:
  wp_storage:
  # db_storage:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/belguabd/data/db
  #     o: bind
  # wp_storage:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/belguabd/data/wp
  #     o: bind